name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## Local LLM MCP ${{ github.ref }}
          
          ### Installation
          
          ```bash
          # Clone the repository
          git clone https://github.com/${{ github.repository }}.git
          cd local-llm-mcp
          
          # Install dependencies
          npm install
          
          # Build the project
          npm run build
          
          # Configure Claude Desktop (see Getting Started guide)
          ```
          
          ### Documentation
          
          - 📚 **[Complete Guide](https://github.com/${{ github.repository }}/blob/main/COMPLETE_GUIDE.md)** - Full technical documentation
          - 🚀 **[Getting Started](https://github.com/${{ github.repository }}/blob/main/GETTING_STARTED.md)** - Step-by-step setup from zero
          
          ### What's New
          
          See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for details.
          
          ### Requirements
          
          - Node.js 18+
          - LM Studio (with a loaded model)
          - Claude Desktop with MCP support
        draft: false
        prerelease: false
